### ISSUE TITLE
[question] PHPCR-ODM support

### ISSUE THREAD

**Issue by yann-eugone** [marmelab/SonataElasticaBundle#10]
Hi,

I was taking a look at the documentation, and I see that you are supporting PHPCR-ODM.
But when I look to the FOSElasticaBundle documentation (or code), I can't see any note about this driver.

I may need this for one of my project, so I may help you testing the integration, and updating the doc about how to process the interaction between elasticsearch and phpcr.

Best regards,
Yann

**Comment by DaphDaOne** [comment]
Hi, and sorry for taking so long to answer you!
This bundle only bypass the SonataAdminBundle for the list view.
It allows to fetch the data directly from an ElasticSearch index instead of a database via the ORM configured for Sonata.

So in the list view there will be no request to PHPCR, the data is retrieved from ElasticSearch directly, the interaction between ElasticSearch and PHPCR is not relevant for this bundle.

**Comment by yann-eugone** [comment]
No problem (we are all busy these days).

Tell me if I'm wrong, but this Bundle rely on FOSElasticaBundle. 
In [FOSElasticaBundle documentation](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md#d-defining-index-types) I've seen that the persistence must be configured for each model to handle with ElasticSearch.

As I read your answer I realise that I may not understand how FOSElasticaBundle is working...

**Comment by DaphDaOne** [comment]
Yes this bundle relies on FosElasticaBundle.
I'm not sure that I understand what your problem is, but it seems that it is not related to the usage of this bundle. Can you explain it to me again ?

**Comment by yann-eugone** [comment]
I don't have any trouble with the usage bundle for now (as I didn't try it yet).
The problem I have, is to understand if I can use it in my project.
I've read the FOSElasticaBundle documentation, and it seems to be required to indicate the persistence type to get the bundle working (as [described in the documentation](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md#d-defining-index-types)).
In my project the persistence is PHPCR, and I wonder if this will be a project or not...

**Comment by DaphDaOne** [comment]
OK, then yes, with PHPCR you will be able to use Sonata with FosElastica & this bundle to display the list view directly from the ES index.

You will just need to use Sonata with the `SonataDoctrinePhpcrAdminBundle`, then configure the persistence in FosElastica with the Doctrine `orm` driver.

**Comment by yann-eugone** [comment]
OK, thank you so. :)

**Comment by DaphDaOne** [comment]
You’re welcome :)
